# Generated by Django 5.1.1 on 2024-09-24 02:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_sale_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=uuid.UUID('d37986c4-3977-409c-818e-a0b642cb0399')),
        ),
    ]
