# Generated by Django 5.1.1 on 2024-09-26 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=uuid.UUID('7eab23db-6a5a-4bcd-80f7-0695567a3053')),
        ),
    ]
