# Generated by Django 5.1.1 on 2024-10-01 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=uuid.UUID('468e0284-e911-46a3-b8fe-27ce6a009a9b')),
        ),
    ]
