# Generated by Django 5.1.1 on 2024-10-01 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=uuid.UUID('cf0349cf-b4eb-4c8e-92ea-c339ec657763')),
        ),
    ]
