# Generated by Django 5.1.1 on 2024-10-01 04:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=uuid.UUID('baabdf87-ce99-4b2b-b3bb-aa64b20b3d7b')),
        ),
    ]
