# Generated by Django 5.1.1 on 2024-10-01 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=uuid.UUID('f2fa1182-146c-4227-9461-966bb7a7d8c8')),
        ),
    ]
