# Generated by Django 5.1.1 on 2024-10-01 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=uuid.UUID('ebbd8564-ccce-488a-8321-5f47610d74af')),
        ),
    ]
