# Generated by Django 5.1.1 on 2024-10-01 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=uuid.UUID('c501b2c6-0003-495d-8118-221140b89b27')),
        ),
    ]
