# Generated by Django 5.1.1 on 2024-10-02 20:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=uuid.UUID('8244b505-76be-4ac3-a5fe-b18939a46fbb')),
        ),
    ]
