# Generated by Django 5.1.1 on 2024-10-02 20:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=uuid.UUID('99516811-86d3-4176-b92e-cca1c8cd9a45')),
        ),
    ]
