# Generated by Django 5.1.1 on 2024-10-04 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=uuid.UUID('63b0208c-0141-4d2a-8590-12c87cebf6d4')),
        ),
    ]
