# Generated by Django 5.1.1 on 2024-10-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shippingcategories_shippinginfo_shipping_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinginfo',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
