# Generated by Django 5.1.1 on 2024-10-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
